# Generated by Django 4.2.25 on 2025-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="personality",
        ),
        migrations.AddField(
            model_name="user",
            name="workos_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
