# Generated by Django 4.2.25 on 2025-12-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="generation_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="topic",
            name="image_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="json_scene",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="mode",
            field=models.CharField(
                choices=[
                    ("single", "Single Image"),
                    ("timeline", "Timeline Mode"),
                    ("map", "Geography Map"),
                    ("quiz", "Quiz Mode"),
                    ("storyboard", "Storyboard"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="SceneVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_scene", models.JSONField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("image_data", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="home.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
