# Generated by Django 4.2.25 on 2025-12-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_topic_generation_status_topic_image_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="diagram",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="generation_status",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="image_data",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="json_scene",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="topic_type",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="visual_story",
        ),
        migrations.AddField(
            model_name="topic",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="current_scene",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="topic",
            name="quiz_scores",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="topic",
            name="scenes_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="scenes_unlocked",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="topic",
            name="subject_type",
            field=models.CharField(
                choices=[("history", "History"), ("geography", "Geography")],
                default="history",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("narration", models.TextField()),
                ("json_scene", models.JSONField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "generation_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("quiz_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="home.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["scene_number"],
                "unique_together": {("topic", "scene_number")},
            },
        ),
    ]
